### PR TITLE
Enforce strict versioning of connect-kit 

### PR DESCRIPTION
**Pull request by sambacha**

### CODE REVIEW

**Review by Hedonismv — APPROVED** [review]
LGTM!

**Review by HenryQW — APPROVED** [review]

**Comment by gustavo-neoswap** [comment]
Prod build failed need to change the version: v1.1.4 already released
image

**Comment by Hedonismv** [comment]
Update to 1.1.8 maybe

https://www.npmjs.com/package/@ledgerhq/connect-kit
here 1.1.7 latest

**Comment by HenryQW** [comment]
#31 should have fixed the version issue

> Update to 1.1.8 maybe
> 
> https://www.npmjs.com/package/@ledgerhq/connect-kit here 1.1.7 latest

No, anything newer than 1.1.4 looks compromised.

**Comment by debych** [comment]
LGTM!

**Comment by Hedonismv** [comment]
> Update to 1.1.8 maybe
> 
> https://www.npmjs.com/package/@ledgerhq/connect-kit here 1.1.7 latest

FInaly 1.1.8 released 😎

**Review by 00MB — APPROVED** [review]
LGTM 😂

**Review by rizoom — APPROVED** [review]

**Comment by tylerchambers** [comment]
more seriously if there's some attachment to using a CDN there should be a SRI check here 

```ts
export async function loadConnectKit(): Promise<LedgerConnectKit> {
  const src = "https://unpkg.com/@ledgerhq/connect-kit@1.1.4/dist/umd/index.js";
  const integrity = "sha384-..."; // Replace with the actual hash
  const globalName = "ledgerConnectKit";

  return new Promise((resolve, reject) => {
    const script = document.createElement('script');
    script.src = src;
    script.integrity = integrity;
    script.crossOrigin = 'anonymous';

    script.onload = () => resolve(window[globalName]);
    script.onerror = () => reject(new Error('Script load error'));

    document.head.appendChild(script);
  });
}
```

**Comment by sambacha** [comment]
> more seriously if there's some attachment to using a CDN there should be a SRI check here 
> 
> 
> 
> ```ts
> 
> export async function loadConnectKit(): Promise<LedgerConnectKit> {
> 
>   const src = "https://unpkg.com/@ledgerhq/connect-kit@1.1.4/dist/umd/index.js";
> 
>   const integrity = "sha384-..."; // Replace with the actual hash
> 
>   const globalName = "ledgerConnectKit";
> 
> 
> 
>   return new Promise((resolve, reject) => {
> 
>     const script = document.createElement('script');
> 
>     script.src = src;
> 
>     script.integrity = integrity;
> 
>     script.crossOrigin = 'anonymous';
> 
> 
> 
>     script.onload = () => resolve(window[globalName]);
> 
>     script.onerror = () => reject(new Error('Script load error'));
> 
> 
> 
>     document.head.appendChild(script);
> 
>   });
> 
> }
> 
> ```

ESM is not compatible with SRI

**Comment by javabudd** [comment]
I was looking for this ticket. It's amazing that they have been publishing straight to NPM with no updates to git, laziness at its finest.

**Comment by RamyEB** [comment]
The connect-kit version is not going to change anymore(Except from us), the loader only aim 1.1.8 (safe version)

**Comment by canderson-ledger** [comment]
Hi all, 

Thank you very much for this Pull Request, it's the right spirit and we're working on one similar removing the dynamic loader entirely and which will enforce installation by NPM.
It's coming

**Comment by ComradeAERGO** [comment]
Thanks to everyone for providing feedback.

We just merged version 1.1.8 of the connect-kit-loader that is tethered to version 1.1.8 of the connect-kit.

From here, we'll now deprecate the connect-kit-loader and advise developers to setup connect-kit manually from npm.

**Pull request closed without merging**
