### PR TITLE
chore: locked cdn version

### PR DESCRIPTION
**Pull request by Volchunovich**
Locked the version to the stable one.

### CODE REVIEW

**Comment by Volchunovich** [comment]
@RamyEB guys maybe we locked cdn version to the stable one?

**Comment by RamyEB** [comment]
The connect-kit version is not going to change anymore(Except from us), for now the loader only aim 1.1.8 (latest and safe version)

**Comment by evgenynacu** [comment]
@RamyEB could you tell more about the fix pls?
connect-kit-loader has url in the code: https://github.com/LedgerHQ/connect-kit/blob/main/packages/connect-kit-loader/src/index.ts#L83C16-L83C68

this url can be cached: https://cdn.jsdelivr.net/npm/@ledgerhq/connect-kit@1

For example, in browser. So users can be still vulnerable. Or am I missing something?

**Comment by Volchunovich** [comment]
@RamyEB until the version is locked we are not safe yet. Your cdn version everytime download the latest one and no package version update will help in such cases

**Comment by RamyEB** [comment]
> @RamyEB until the version is locked we are not safe yet. Your cdn version everytime download the latest one and no package version update will help in such cases

Thank you for your suggestion.

The connect-kit version is not going to change anymore (Except from us).
Now the loader only aim 1.1.8 (latest and safe version).

We're currently working on the best possible solution.

**Comment by ComradeAERGO** [comment]
> @RamyEB until the version is locked we are not safe yet. Your cdn version everytime download the latest one and no package version update will help in such cases
> 
> How do I know that some 1.1.9 version will not be downloaded from this https://cdn.jsdelivr.net/npm/@ledgerhq/connect-kit@1? and it won't be a malicious version?
> 
> if you will be locked the cdn version we could be also locked your package version and it will be more safety for us.

All rights to push on npmjs have been revoked except for 2 key maintainers.

For the path forward for connect-kit, we are considering several options, like removing dynamic loading altogether.

**Comment by Volchunovich** [comment]
@ComradeAERGO sounds great!

**Comment by 409H** [comment]
> The connect-kit version is not going to change anymore(Except from us)

How can you guarantee that?

**Comment by ComradeAERGO** [comment]
> > The connect-kit version is not going to change anymore(Except from us)
> 
> How can you guarantee that?

https://github.com/LedgerHQ/connect-kit/pull/36#issuecomment-1856206575

**Comment by glitch-txs** [comment]
I mean, wouldn't this be an extra measurement of security using a fixed version? I don't see any harm in merging this.

**Comment by ComradeAERGO** [comment]
@Volchunovich 

We're merging your PR and releasing a new version of the connect-kit loader.
This version will be the last.

As a next step, we'll sunset the connect-kit loader and push developers to install connect-kit from their package manager directly.

**Comment by Volchunovich** [comment]
@ComradeAERGO great news! Thanks

**Pull request merged**
